import pyautogui as task
import time

while True:
    screenWidth, screenHeight = task.size()
    currentMouseX, currentMouseY = task.position()
    time.sleep(2)
    task.moveTo(100, 1060)
    task.click()
    time.sleep(2)
    task.write("Andro")
    time.sleep(2)
    task.press('enter')
    time.sleep(15)
    task.moveTo(1080, 190)
    time.sleep(2)
    task.click()
    time.sleep(3)
    task.moveTo(1080, 480)
    time.sleep(1)
    task.click()
    time.sleep(1)
    task.moveTo(1200, 750)
    time.sleep(1)
    task.click()
    time.sleep(2)
    task.moveTo(800, 265)
    time.sleep(2)
    task.doubleClick()
    task.click()
    time.sleep(2)
    task.write("Digital School")
    time.sleep(2)
    task.moveTo(800, 320)
    time.sleep(2)
    task.doubleClick()
    task.click()
    time.sleep(2)
    task.write("com.approxsoft.digitalschool")
    time.sleep(2)
    task.moveTo(1350, 745)
    time.sleep(1)
    task.click()
    time.sleep(10)
    task.moveTo(0, 0)

